name: CLJS Testing

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run:  npm install
    - name: Compile tests
      if: ${{ success() }}
      run: npx shadow-cljs compile test
    - name: Run tests
      if: ${{ success() }}
      run: node out/node-tests.js
